name: localtunnel
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Tan Yuanhong <leotan.yh@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
 observable: ^0.22.2
 json_serializable: ^3.0.0
 dio: ^2.1.5

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  http_server: ^0.9.8+1
